### ISSUE TITLE
Feature Request : Add dark mode toggle button ! 🔆

### ISSUE THREAD

**Issue by abhisheksurve45** [abhisheksurve45/abhisheksurve45.github.io#2]
**Is your feature request related to a problem? Please describe.**

Toggle button for dark mode!

**Describe the solution you'd like**

Similar to : https://ryanfeigenbaum.com/dark-mode/

![image](https://user-images.githubusercontent.com/36799020/95069455-5028cb80-0724-11eb-96bf-f57d18019c35.png)

**Describe alternatives you've considered**

Example is just for representation, new ideas are welcome!

**Additional context**

Examples : 

1. https://codepen.io/demilad/pen/bZRjpb
2. https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by RitikaShrestha-me** [comment]
Would like do this task

**Comment by dipan010** [comment]
can i contribute?

**Comment by abhisheksurve45** [comment]
Hi, @RitikaShrestha-me , thank you for showing interest in the mentioned feature request for my personal website. Please feel free to work upon it. Thanks and regards.

**Comment by abhisheksurve45** [comment]
Hi @dipan010 , @RitikaShrestha-me  has picked up this task, however if it is not actively worked upon, I'll let you know the same and you can start with it. Again, thanks for showing interest in my repo. Happy Hacktober!

**Comment by paramaDEV** [comment]
Can I work in here?
